dietplanr/api/urls.py
from rest_framework.routers import DefaultRouter
from rest_framework.urlpatterns import path, include

from .views import AppointmentsView, PersonalizeRecipeView, AppointmentDetailView, ClientsView, NotificationsView, MyProfileView
app_name = 'api'
router = DefaultRouter()
router.register(r'get-appointments', AppointmentsView, basename='appointments')

urlpatterns = [
    path('appointments/<int:pk>/', AppointmentDetailView.as_view(), name='appointments-detail'),

    path('appointments/<int:year>/<int:month>', AppointmentsView.as_view(), name='appointments-list'),
    path('recipes/<int:id>/personalize/', PersonalizeRecipeView.as_view(), name='personalize-recipe'),
    path('clients/', ClientsView.as_view(), name='clients-list'),
    path('notifications/', NotificationsView.as_view(), name='notification-list'),
    path('notifications/<int:id>', ClientsView.as_view(), name='notification-details'),
    path('my-profile/', MyProfileView.as_view(), name='notification-details'),

    # path('create-appointment/', CreateAppointmentView.as_view(), name='create_appointment'),

    # path('clients/<int:id>/', ClientsDetailView.as_view(), name='clients-detail'),
    # path('clients/', ClientsView.as_view(), name='clients-list'),
]

dietplanr/dietplanr/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include
from django.views import View

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls', namespace='chat')),
    path('', include('panel.urls', namespace='panel')),
    path('tracker/', include('tracker.urls', namespace='tracker')),
    path('api/', include('api.urls', namespace='api')),
]

dietplanr/panel/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import (ClientProfileEditView,
                    DietitianProfileEditView,
                    CreateAppointmentView,
                    ManageClientsView,
                    EditAccount,
                    Home,
                    DisplayDietitianProfile,
                    ManageCalendar,
                    ManageRecipesView,
                    ManageDietitianProfileView)

app_name = 'panel'
urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('user/edit-profile/', ClientProfileEditView.as_view(), name='user_edit_profile'),
    path('dietitian/edit-profile/', DietitianProfileEditView.as_view(), name='edit_profile'),
    path('account/edit', EditAccount.as_view(), name='edit_account'),
    path('appointment/<slug:dietitian_slug>/', CreateAppointmentView.as_view(), name='appointment'),
    path('account/register/', EditAccount.as_view(), name='registration'),
    path('clients/', ManageClientsView.as_view(), name='show_clients'),
    path('login/', LoginView.as_view(), name='login'),
    path('account/logout/', LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('dietitians/<slug:dietitian_slug>', DisplayDietitianProfile.as_view(), name='show_clients'),
    path('calendar/', ManageCalendar.as_view(), name='show_calendar'),
    path('recipes/', ManageRecipesView.as_view(), name='show_recipes'),
    path('profile/', ManageDietitianProfileView, name="show_profile")
]

dietplanr/panel/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import DietitianProfile, ClientProfile, Appointment, CustomUser
from django.conf import settings


class ClientProfileForm(forms.ModelForm):
    class Meta:
        model = ClientProfile
        fields = ['dietitian']


class DietitianProfileForm(forms.ModelForm):
    class Meta:
        model = DietitianProfile
        fields = ['user', 'specialty',
                  'experience', 'nutritional_philosophy',
                  'some_more']


class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ['title', 'event_duration',
                  'date']
    # def clean_data(self):
    #     cd = self.cleaned_data[]


class UserAccountForm(forms.ModelForm):
    age = forms.IntegerField(label='Age', required=False, initial=None)  # Dodaj pole "age" do formularza

    class Meta:
        model = CustomUser
        fields = ['email', 'password', 'first_name', 'last_name',
                  'is_dietitian', 'is_client', 'gender',
                  'City', 'Country', 'photo', 'full_name',
                  'date_of_birth']

    def save_age(self, user):  # Metoda do zapisywania wartości "age" w modelu ClientProfile
        age = self.cleaned_data.get('age')
        if age:
            client_profile, created = ClientProfile.objects.get_or_create(user=user)
            client_profile.age = age
            client_profile.save()

    # def clean_date_of_birth(self):
    #     cleaned_data = super().clean()
    #     date_of_birth = cleaned_data.get('date_of_birth')
    #     if date_of_birth and date_of_birth >= timezone.now().date():
    #         raise ValidationError('Data urodzin nie może być w przyszłości.')
    #     return date_of_birth

dietplanr/panel/views.py
import json

from django.contrib.auth import login
from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseNotFound
from django.shortcuts import get_object_or_404, redirect
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView, DetailView
import calendar
from datetime import datetime
from itertools import groupby
from operator import attrgetter

from dietplanr.utils import ClientRequiredMixin, DietitianRequiredMixin
from recipes.models import Recipe
# Create your views here.
from .forms import AppointmentForm, ClientProfileForm, DietitianProfileForm, UserAccountForm
from .models import DietitianProfile, CustomUser, ClientProfile, Appointment


class Home(LoginRequiredMixin, View):
    template_name = 'panel/home.html'

    def get(self, request):
        return render(request, self.template_name)


class DisplayDietitianProfile(LoginRequiredMixin, DetailView):
    template_name = 'panel/dietitian_profile.html'
    context_object_name = 'dietitian'

    def get_object(self, queryset=None):
        profile_slug = self.kwargs.get('dietitian_slug')
        profile_account = get_object_or_404(CustomUser, slug=profile_slug)
        dietitian_profile = get_object_or_404(DietitianProfile, user=profile_account)
        return dietitian_profile

    def get_clients_and_appointments(self, dietitian_profile):
        clients = ClientProfile.objects.filter(dietitian=dietitian_profile)
        appointments = Appointment.objects.filter(dietitian_profile=dietitian_profile)
        return clients, appointments

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        dietitian_profile = self.get_object()
        clients, appointments = self.get_clients_and_appointments(dietitian_profile)

        context.update(dietitian_profile.user.get_user_data())
        context['appointments'] = appointments
        context['clients'] = clients
        context['dietitian_profile'] = dietitian_profile
        return context


class CreateEventView(ListView):
    pass


class OwnerEditMixin:
    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ManageRecipesView(DietitianRequiredMixin, ListView):
    model = Recipe
    template_name = 'panel/recipes_list.html'
    context_object_name = 'recipes'

    def get_queryset(self):
        qs = super().get_queryset()

        # TODO return only recipes of current dietitian
        return qs.filter(author=self.request.user)


class ManageSettings(ListView):
    # model = Client
    template_name = 'panel/dietitian_panel.html'

    def get_queryset(self):
        qs = super().get_queryset()
        # TODO return only recipes of current dietitian
        # return qs.filter()


def show_notifications(request):
    pass


class EditAccount(View):
    template_name = 'panel/registration.html'
    form_class = UserAccountForm

    def get(self, request):
        if request.user.is_authenticated:
            form = self.form_class(instance=request.user)
        else:
            form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.password = make_password(form.cleaned_data['password'])  # Haszowanie hasła
            user.save()

            if user:
                login(request, user)
                print('Użytkownik zalogowany:')
                redirect('panel:home')

        return render(request, self.template_name, {'form': form})


class ClientProfileEditView(ClientRequiredMixin, View):
    form_class = ClientProfileForm
    template_name = 'panel/user_profile_edit.html'

    def get_client_profile(self):
        return get_object_or_404(ClientProfile, user=self.request.user)

    def get(self, request):
        print('Zalogowany użytkownik:', request.user)
        client_profile = self.get_client_profile()
        form = self.form_class(instance=client_profile)
        return render(request, self.template_name, {'form': form})

    def save_form(self, form):
        client_profile = self.get_client_profile()
        if form.is_valid():
            form.save()
            return True
        return False

    def post(self, request):
        form = self.form_class(request.POST, instance=self.get_client_profile())
        if self.save_form(form):
            return redirect('panel:home')
        return render(request, self.template_name, {'form': form})


class CreateAppointmentView(View):
    def get(self, request, dietitian_slug):
        if dietitian_slug:
            dietitian_account = get_object_or_404(CustomUser, slug=dietitian_slug)
            dietitian_profile = DietitianProfile.objects.filter(user=dietitian_account).first()
            if dietitian_profile is not None and dietitian_account.is_dietitian:
                form = AppointmentForm()
                return render(request, 'panel/appointment_set.html', {'form': form})
        return HttpResponseNotFound("Użytkownik nie jest dietetykiem.")

    def post(self, request, dietitian_slug):
        form = AppointmentForm(request.POST)
        dietitian_account = get_object_or_404(CustomUser, slug=dietitian_slug)
        dietitian_profile = get_object_or_404(DietitianProfile, user=dietitian_account)
        user_profile = request.user
        if form.is_valid():
            appointment = form.save(commit=False)
            appointment.dietitian_profile = dietitian_profile
            appointment.user_profile = user_profile
            appointment.save()
            return HttpResponse("<html><body>Spotkanie utworzone</body></html>")
        return render(request, 'panel/appointment_set.html', {'form': form})


class DietitianProfileEditView(DietitianRequiredMixin, View):
    form_class = DietitianProfileForm

    def get(self, request):
        dietitian_profile = DietitianProfile.objects.get(user=request.user)
        form = self.form_class(instance=dietitian_profile)
        return render(request, 'panel/dietitian_profile_edit.html', {'form': form})

    def post(self, request):
        dietitian_profile = get_object_or_404(DietitianProfile, user=request.user)
        form = DietitianProfileForm(request.POST, instance=dietitian_profile)
        if form.is_valid():
            form.save()
            return redirect('panel:home')
        return render(request, 'panel/dietitian_profile_edit.html', {'form': form})


class ManageClientsView(DietitianRequiredMixin, ListView):
    model = ClientProfile
    template_name = 'panel/dietitian_panel.html'
    context_object_name = 'clients'

    def get_queryset(self):
        qs = super().get_queryset()
        dietitian_profile = get_object_or_404(DietitianProfile, user=self.request.user)
        return qs.filter(dietitian=dietitian_profile)


class CalendarAppointmentsMixin:
    def get_appointments(self, user, year, month):
        if hasattr(user, 'dietitianprofile'):
            dietitian_profile = user.dietitianprofile
            return dietitian_profile.get_dietitian_appointments(year, month)

        else:
            return user.get_user_appointments()


class ManageCalendar(LoginRequiredMixin, ListView, CalendarAppointmentsMixin):
    template_name = 'panel/calendar.html'
    context_object_name = 'appointments'

    def get_queryset(self, year, month):
        return self.get_appointments(self.request.user, year, month)

    def get(self, request):
        return self._handle_calendar_request(request)

    def post(self, request):
        return self._handle_calendar_request(request)

    def _handle_calendar_request(self, request):
        selected_year = int(request.POST.get('year', datetime.now().year))
        selected_month = int(request.POST.get('month', datetime.now().month))
        current_day_num = datetime.now().day
        first_day = datetime(selected_year, selected_month, 1)
        weekday_of_start = first_day.weekday()
        last_day = calendar.monthrange(selected_year, selected_month)[1]
        prev_month = selected_month - 1 if selected_month > 1 else 12
        last_day_prev_month = calendar.monthrange(selected_year, prev_month)[1]

        months = {i: month_name for i, month_name in enumerate(calendar.month_name) if i != 0}
        years_range = range(2023, 2028)
        weekdays = calendar.day_name

        prev_days = range(last_day_prev_month - weekday_of_start + 1, last_day_prev_month + 1)
        next_days = range(1, 42 - last_day - weekday_of_start + 1)
        current_month = datetime.now().month
        month_name = calendar.month_name[current_month]
        appointments = self.get_queryset(selected_year, selected_month)
        sorted_appointments = sorted(appointments, key=attrgetter("date"))
        grouped_appointments = []
        for date, group in groupby(sorted_appointments, key=lambda app: app.date.date()):
            grouped_appointments.append(list(group))
        context = {
            "current_date": datetime.now(),
            "current_year": datetime.now().year,
            "current_month": month_name,
            "current_day_num": current_day_num,
            "selected_year": selected_year,
            "selected_month": selected_month,
            "years": years_range,
            "months": months,
            "weekdays": weekdays,
            "prev_days": prev_days,
            "days": range(1, last_day + 1),
            "next_days": next_days,
            "grouped_appointments": grouped_appointments,
        }
        return render(request, "panel/calendar.html", context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user

        if hasattr(user, 'dietitianprofile'):

dietplanr/panel/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/5e1f2a52bc.js" crossorigin="anonymous"></script>
    <script src="{% static "js/chat.js" %}" defer type="module"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@600;900&display=swap" rel="stylesheet">

    {% block stylesheets %}{% endblock %}
    {% block scripts %}{% endblock %}
</head>
<body>
<nav class="navbar">
    <i class="fa-solid fa-bars" id="bars"></i>
    <div class="list-wrapper" id="list-wrapper">
        <ul>
            <li><a href="{% url 'panel:home' %}">Home</a></li>
            <li><a href="">Features</a></li>
            <li><a href="{% url 'panel:show_profile' %}">View your profile</a></li>
            <li><a href="">FAQ</a></li>
        </ul>
    </div>
    <div class="last">
        {% if user.is_authenticated %}
            <div class="chat-list" data-notification-count="0" data-chat-list>
                <i class="fa-regular fa-message fa-lg" id="chat-icon"></i>
                <div class="conversations d-none" id="conversations"></div>
            </div>
        {% endif %}
        <ul class="user-action" id="user-action">
            <a class="user-box">
                <i class="fa-regular fa-user fa-lg"></i>
                <div class="name">
                    {% if user.is_authenticated %}
                        {{ user.first_name }}
                        <span class="d-none" id="user_id">{{ user.id }}</span>
                    {% else %}
                        Guest
                    {% endif %}
                </div>
                <i class="fa-solid fa-angle-down fa-sm"></i>
            </a>
            <ul class="action-list d-none">
                {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'panel:logout' %}">Wyloguj się</a>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'panel:login' %}">Zaloguj się</a>
                    </li>
                    <li>
                        <a href="{% url 'panel:registration' %}">Rejestracja</a>
                    </li>
                {% endif %}
            </ul>
        </ul>
    </div>
</nav>
<template data-chat-template>
    <div class="chat-wrapper" data-chat>
        <div class="chat">
            <div class="chat-name-wrapper">
                <div class="name-user-block">
                    <i class="fa-regular fa-user fa-xl"></i>
                    <div class="chat-name"></div>
                </div>
                <i class="fa-solid fa-xmark"></i>
            </div>
            <div data-chat-log class="custom-chat-log">
            </div>
            <div class="message-form">
                <div class="message-input">
                    <input type="text" placeholder="Enter your chat message here" class="chatMessageInput"
                           data-chat-message-input>
                </div>
                <button class="d-none" data-chat-message-send></button>
            </div>
        </div>
    </div>
</template>
<div id="content">
    {% block content %}

    {% endblock %}
</div>
{% if not user.is_authenticated %}
    <footer>
        <div>
            <p>
                Ready start your journey to better
            </p>
            <p>
                health and nutrition, Your body
            </p>
            <p>
                deserves?
            </p>
        </div>
        <div>
            <div>
                <p>
                    No account?
                </p>
                <p style="text-indent: 1rem;">
                    No problem
                </p>
            </div>
            <a href="{% url 'panel:registration' %}" class="register">REGISTER</a>
        </div>
    </footer>
{% endif %}
</body>
</html>

dietplanr/panel/templates/dietitian_panel_base.html
{% extends 'base.html' %}
{% load static %}
{% block stylesheets %}
    <link href="{% static "css/dietitian_panel_base.css" %}" rel="stylesheet">
    {% block additional_stylesheets %}
    {% endblock %}
{% endblock %}
{% block scripts %}
    {% block additional_scripts %}
    {% endblock %}
{% endblock %}
{% block content %}
    <div class="container">
        <nav class="sidebar" data-sidebar>
            <a href="{% url 'panel:show_clients' %}" data-sidebar-link>Clients</a>
            <a href="{% url 'panel:show_recipes' %}" data-sidebar-link>Recipes</a>
            <a href="{% url 'panel:show_calendar' %}" data-sidebar-link>Calendar</a>
            <a href="{% url 'panel:edit_profile' %}" data-sidebar-link>Settings</a>
        </nav>
        {% block information %}
        {% endblock %}
    </div>
{% endblock %}