dietplanr/api/urls.py
from rest_framework.routers import DefaultRouter
from rest_framework.urlpatterns import path, include

from .views import AppointmentsView, PersonalizeRecipeView, AppointmentDetailView, ClientsView, NotificationsView, MyProfileView
app_name = 'api'
router = DefaultRouter()
router.register(r'get-appointments', AppointmentsView, basename='appointments')

urlpatterns = [
    path('appointments/<int:pk>/', AppointmentDetailView.as_view(), name='appointments-detail'),

    path('appointments/<int:year>/<int:month>', AppointmentsView.as_view(), name='appointments-list'),
    path('recipes/<int:id>/personalize/', PersonalizeRecipeView.as_view(), name='personalize-recipe'),
    path('clients/', ClientsView.as_view(), name='clients-list'),
    path('notifications/', NotificationsView.as_view(), name='notification-list'),
    path('notifications/<int:id>', ClientsView.as_view(), name='notification-details'),
    path('my-profile/', MyProfileView.as_view(), name='notification-details'),

    # path('create-appointment/', CreateAppointmentView.as_view(), name='create_appointment'),

    # path('clients/<int:id>/', ClientsDetailView.as_view(), name='clients-detail'),
    # path('clients/', ClientsView.as_view(), name='clients-list'),
]

dietplanr/dietplanr/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include
from django.views import View

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls', namespace='chat')),
    path('', include('panel.urls', namespace='panel')),
    path('tracker/', include('tracker.urls', namespace='tracker')),
    path('api/', include('api.urls', namespace='api')),
]

dietplanr/panel/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import (ClientProfileEditView,
                    DietitianProfileEditView,
                    CreateAppointmentView,
                    ManageClientsView,
                    EditAccount,
                    Home,
                    DisplayDietitianProfile,
                    ManageCalendar,
                    ManageRecipesView,
                    ManageDietitianProfileView)

app_name = 'panel'
urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('user/edit-profile/', ClientProfileEditView.as_view(), name='user_edit_profile'),
    path('dietitian/edit-profile/', DietitianProfileEditView.as_view(), name='edit_profile'),
    path('account/edit', EditAccount.as_view(), name='edit_account'),
    path('appointment/<slug:dietitian_slug>/', CreateAppointmentView.as_view(), name='appointment'),
    path('account/register/', EditAccount.as_view(), name='registration'),
    path('clients/', ManageClientsView.as_view(), name='show_clients'),
    path('login/', LoginView.as_view(), name='login'),
    path('account/logout/', LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('dietitians/<slug:dietitian_slug>', DisplayDietitianProfile.as_view(), name='show_clients'),
    path('calendar/', ManageCalendar.as_view(), name='show_calendar'),
    path('recipes/', ManageRecipesView.as_view(), name='show_recipes'),
    path('profile/', ManageDietitianProfileView, name="show_profile")
]

dietplanr/tracker/urls.py
from django.contrib.auth.urls import path
from .forms import ActivityForm
from .views import RegisterActivity
urlpatterns = [
    path('register-activity/', RegisterActivity.as_view(), name='register_activity')
]

app_name = 'tracker'

dietplanr/panel/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import DietitianProfile, ClientProfile, Appointment, CustomUser
from django.conf import settings


class ClientProfileForm(forms.ModelForm):
    class Meta:
        model = ClientProfile
        fields = ['dietitian']


class DietitianProfileForm(forms.ModelForm):
    class Meta:
        model = DietitianProfile
        fields = ['user', 'specialty',
                  'experience', 'nutritional_philosophy',
                  'some_more']


class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ['title', 'event_duration',
                  'date']
    # def clean_data(self):
    #     cd = self.cleaned_data[]


class UserAccountForm(forms.ModelForm):
    age = forms.IntegerField(label='Age', required=False, initial=None)  # Dodaj pole "age" do formularza

    class Meta:
        model = CustomUser
        fields = ['email', 'password', 'first_name', 'last_name',
                  'is_dietitian', 'is_client', 'gender',
                  'City', 'Country', 'photo', 'full_name',
                  'date_of_birth']

    def save_age(self, user):  # Metoda do zapisywania wartości "age" w modelu ClientProfile
        age = self.cleaned_data.get('age')
        if age:
            client_profile, created = ClientProfile.objects.get_or_create(user=user)
            client_profile.age = age
            client_profile.save()

    # def clean_date_of_birth(self):
    #     cleaned_data = super().clean()
    #     date_of_birth = cleaned_data.get('date_of_birth')
    #     if date_of_birth and date_of_birth >= timezone.now().date():
    #         raise ValidationError('Data urodzin nie może być w przyszłości.')
    #     return date_of_birth

dietplanr/panel/views.py
import json

from django.contrib.auth import login
from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseNotFound
from django.shortcuts import get_object_or_404, redirect
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView, DetailView
import calendar
from datetime import datetime
from itertools import groupby
from operator import attrgetter

from dietplanr.utils import ClientRequiredMixin, DietitianRequiredMixin
from recipes.models import Recipe
# Create your views here.
from .forms import AppointmentForm, ClientProfileForm, DietitianProfileForm, UserAccountForm
from .models import DietitianProfile, CustomUser, ClientProfile, Appointment


class Home(LoginRequiredMixin, View):
    template_name = 'panel/home.html'

    def get(self, request):
        return render(request, self.template_name)


class DisplayDietitianProfile(LoginRequiredMixin, DetailView):
    template_name = 'panel/dietitian_profile.html'
    context_object_name = 'dietitian'

    def get_object(self, queryset=None):
        profile_slug = self.kwargs.get('dietitian_slug')
        profile_account = get_object_or_404(CustomUser, slug=profile_slug)
        dietitian_profile = get_object_or_404(DietitianProfile, user=profile_account)
        return dietitian_profile

    def get_clients_and_appointments(self, dietitian_profile):
        clients = ClientProfile.objects.filter(dietitian=dietitian_profile)
        appointments = Appointment.objects.filter(dietitian_profile=dietitian_profile)
        return clients, appointments

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        dietitian_profile = self.get_object()
        clients, appointments = self.get_clients_and_appointments(dietitian_profile)

        context.update(dietitian_profile.user.get_user_data())
        context['appointments'] = appointments
        context['clients'] = clients
        context['dietitian_profile'] = dietitian_profile
        return context


class CreateEventView(ListView):
    pass


class OwnerEditMixin:
    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ManageRecipesView(DietitianRequiredMixin, ListView):
    model = Recipe
    template_name = 'panel/recipes_list.html'
    context_object_name = 'recipes'

    def get_queryset(self):
        qs = super().get_queryset()

        # TODO return only recipes of current dietitian
        return qs.filter(author=self.request.user)


class ManageSettings(ListView):
    # model = Client
    template_name = 'panel/dietitian_panel.html'

    def get_queryset(self):
        qs = super().get_queryset()
        # TODO return only recipes of current dietitian
        # return qs.filter()


def show_notifications(request):
    pass


class EditAccount(View):
    template_name = 'panel/registration.html'
    form_class = UserAccountForm

    def get(self, request):
        if request.user.is_authenticated:
            form = self.form_class(instance=request.user)
        else:
            form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.password = make_password(form.cleaned_data['password'])  # Haszowanie hasła
            user.save()

            if user:
                login(request, user)
                print('Użytkownik zalogowany:')
                redirect('panel:home')

        return render(request, self.template_name, {'form': form})


class ClientProfileEditView(ClientRequiredMixin, View):
    form_class = ClientProfileForm
    template_name = 'panel/user_profile_edit.html'

    def get_client_profile(self):
        return get_object_or_404(ClientProfile, user=self.request.user)

    def get(self, request):
        print('Zalogowany użytkownik:', request.user)
        client_profile = self.get_client_profile()
        form = self.form_class(instance=client_profile)
        return render(request, self.template_name, {'form': form})

    def save_form(self, form):
        client_profile = self.get_client_profile()
        if form.is_valid():
            form.save()
            return True
        return False

    def post(self, request):
        form = self.form_class(request.POST, instance=self.get_client_profile())
        if self.save_form(form):
            return redirect('panel:home')
        return render(request, self.template_name, {'form': form})


class CreateAppointmentView(View):
    def get(self, request, dietitian_slug):
        if dietitian_slug:
            dietitian_account = get_object_or_404(CustomUser, slug=dietitian_slug)
            dietitian_profile = DietitianProfile.objects.filter(user=dietitian_account).first()
            if dietitian_profile is not None and dietitian_account.is_dietitian:
                form = AppointmentForm()
                return render(request, 'panel/appointment_set.html', {'form': form})
        return HttpResponseNotFound("Użytkownik nie jest dietetykiem.")

    def post(self, request, dietitian_slug):
        form = AppointmentForm(request.POST)
        dietitian_account = get_object_or_404(CustomUser, slug=dietitian_slug)
        dietitian_profile = get_object_or_404(DietitianProfile, user=dietitian_account)
        user_profile = request.user
        if form.is_valid():
            appointment = form.save(commit=False)
            appointment.dietitian_profile = dietitian_profile
            appointment.user_profile = user_profile
            appointment.save()
            return HttpResponse("<html><body>Spotkanie utworzone</body></html>")
        return render(request, 'panel/appointment_set.html', {'form': form})


class DietitianProfileEditView(DietitianRequiredMixin, View):
    form_class = DietitianProfileForm

    def get(self, request):
        dietitian_profile = DietitianProfile.objects.get(user=request.user)
        form = self.form_class(instance=dietitian_profile)
        return render(request, 'panel/dietitian_profile_edit.html', {'form': form})

    def post(self, request):
        dietitian_profile = get_object_or_404(DietitianProfile, user=request.user)
        form = DietitianProfileForm(request.POST, instance=dietitian_profile)
        if form.is_valid():
            form.save()
            return redirect('panel:home')
        return render(request, 'panel/dietitian_profile_edit.html', {'form': form})


class ManageClientsView(DietitianRequiredMixin, ListView):
    model = ClientProfile
    template_name = 'panel/dietitian_panel.html'
    context_object_name = 'clients'

    def get_queryset(self):
        qs = super().get_queryset()
        dietitian_profile = get_object_or_404(DietitianProfile, user=self.request.user)
        return qs.filter(dietitian=dietitian_profile)


class CalendarAppointmentsMixin:
    def get_appointments(self, user, year, month):
        if hasattr(user, 'dietitianprofile'):
            dietitian_profile = user.dietitianprofile
            return dietitian_profile.get_dietitian_appointments(year, month)

        else:
            return user.get_user_appointments()


class ManageCalendar(LoginRequiredMixin, ListView, CalendarAppointmentsMixin):
    template_name = 'panel/calendar.html'
    context_object_name = 'appointments'

    def get_queryset(self, year, month):
        return self.get_appointments(self.request.user, year, month)

    def get(self, request):
        return self._handle_calendar_request(request)

    def post(self, request):
        return self._handle_calendar_request(request)

    def _handle_calendar_request(self, request):
        selected_year = int(request.POST.get('year', datetime.now().year))
        selected_month = int(request.POST.get('month', datetime.now().month))
        current_day_num = datetime.now().day
        first_day = datetime(selected_year, selected_month, 1)
        weekday_of_start = first_day.weekday()
        last_day = calendar.monthrange(selected_year, selected_month)[1]
        prev_month = selected_month - 1 if selected_month > 1 else 12
        last_day_prev_month = calendar.monthrange(selected_year, prev_month)[1]

        months = {i: month_name for i, month_name in enumerate(calendar.month_name) if i != 0}
        years_range = range(2023, 2028)
        weekdays = calendar.day_name

        prev_days = range(last_day_prev_month - weekday_of_start + 1, last_day_prev_month + 1)
        next_days = range(1, 42 - last_day - weekday_of_start + 1)
        current_month = datetime.now().month
        month_name = calendar.month_name[current_month]
        appointments = self.get_queryset(selected_year, selected_month)
        sorted_appointments = sorted(appointments, key=attrgetter("date"))
        grouped_appointments = []
        for date, group in groupby(sorted_appointments, key=lambda app: app.date.date()):
            grouped_appointments.append(list(group))
        context = {
            "current_date": datetime.now(),
            "current_year": datetime.now().year,
            "current_month": month_name,
            "current_day_num": current_day_num,
            "selected_year": selected_year,
            "selected_month": selected_month,
            "years": years_range,
            "months": months,
            "weekdays": weekdays,
            "prev_days": prev_days,
            "days": range(1, last_day + 1),
            "next_days": next_days,
            "grouped_appointments": grouped_appointments,
        }
        return render(request, "panel/calendar.html", context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user

        if hasattr(user, 'dietitianprofile'):

dietplanr/panel/templates/panel/appointment_set.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Zapisz spotkanie">
</form>

dietplanr/panel/templates/panel/calendar.html
{% extends 'dietitian_panel_base.html' %}
{% load static %}
{% block title %}Calendar{% endblock %}
{% block additional_stylesheets %}
    <link href="{% static "css/calendar.css" %}" rel="stylesheet">{% endblock %}
{% block additional_scripts %}
    <script src="{% static "js/calendar.js" %}"
            defer></script>
{% endblock %}
{% block information %}
    {% csrf_token %}
    <script>
        const csrfToken = "{{ csrf_token }}";
    </script>
    <div class="calendar-container" data-container>
        <header>
            <div id="selected_year" class="d-none">{{ selected_year }}</div>
            <div id="selected_month" class="d-none">{{ selected_month }}</div>
            <div class="button-container">
                <button class="month-button" id="month-button">{{ current_month }}-{{ current_year }}</button>
                <button class="year-button" id="year-button" style="display: none;">{{ current_year }}</button>
                <button class="ten-years-button" id="ten-years-button" style="display: none;">2020-2030</button>
            </div>
            <div class="arrows-wrapper">
                <i class="fa-solid fa-angle-up" id="arrow-up"></i>
                <i class="fa-solid fa-angle-down" id="arrow-down"></i>
            </div>
        </header>
        <div class="calendar from-up">
            {% for weekday in weekdays %}
                <div class="weekday">{{ weekday }}</div>
            {% endfor %}
            {% for day in prev_days %}
                <div class="diff_day" data-prev-day="{{ day }}">{{ day }}</div>
            {% endfor %}
            {% for day in days %}
                <div data-day="{{ day }}"
                     class="day{% if selected_year == current_date.year and selected_month == current_date.month and day == current_day_num %} current_day{% endif %}">
                    {{ day }}
                    {% for group in grouped_appointments %}
                        {% for appointment in group %}
                            {% if appointment.date.year == selected_year and appointment.date.month == selected_month and appointment.date.day == day %}
                                {% if group|length > 1 %}
                                    {% if forloop.first %}
                                        <div class="appointment-count" data-appointment-count="{{ group|length }}"
                                             data-value="{{ appointment.date|date:"Y-m-d" }}">
                                            Appointment count: {{ group|length }}
                                        </div>
                                    {% endif %}
                                {% elif group|length == 1 %}
                                    <div class="appointment" draggable="true"
                                         data-appointment="{{ appointment.date|date:"Y-m-d" }}"
                                         data-id="{{ appointment.id }}">
                                        <div class="time">
                                            {{ appointment.date|date:"H:i" }}
                                        </div>
                                        <div class="title">
                                            {{ appointment.title }}
                                        </div>
                                        <div class="duration">
                                            Duration: {{ appointment.event_duration }}
                                        </div>
                                    </div>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    {% endfor %}
                </div>
            {% endfor %}
            {% for day in next_days %}
                <div class="diff_day" data-next-day="{{ day }}">{{ day }}</div>
            {% endfor %}
        </div>
    </div>
    <template data-appointment-template>
        <div class="appointment" data-appointment draggable="true">
            <div class="time"></div>
            <div class="title"></div>
            <div class="duration"></div>
        </div>
    </template>
    <template data-dialog-form-template>
        <form class="d-none dialog-form">
            <div class="title"></div>
            <input type="text" name="title">
            <select name="duration">
                <option value="30:00">30:00</option>
                <option value="60:00">60:00</option>
            </select>
            <input type="time" name="time">
            <button data-dialog-form-button>SUBMIT</button>
            <button data-delete-appointment>DELETE</button>
        </form>
    </template>
    <dialog class="appointment-dialog" data-appointment-dialog>
        <form method="POST">
            <button formmethod="dialog" type="submit" data-dialog-close>
                <i class="fa-solid fa-xmark"></i>
            </button>
        </form>
        <div class="content">
            {% for group in grouped_appointments %}
                {% for appointment in group %}
                    <form class="d-none dialog-form" data-dialog-content="{{ appointment.date|date:"Y-m-d" }}"
                          data-id="{{ appointment.id }}">
                        <div class="title">{{ appointment.title }}</div>
                        <input type="text" name="title" value="{{ appointment.title }}">
                        <select name="duration">
                            <option value="30:00">30:00</option>
                            <option value="60:00">60:00</option>
                        </select>
                        <input type="time" value="{{ appointment.date|date:"H:i" }}">
                        <button data-dialog-form-button>SUBMIT</button>
                        <button data-delete-appointment>DELETE</button>
                    </form>
                {% endfor %}
            {% endfor %}
        </div>
    </dialog>
{% endblock %}

dietplanr/panel/templates/panel/clientprofile_list.html
{% extends 'dietitian_panel_base.html' %}
{% load static %}
{% block title %}Clients{% endblock %}
{% block additional_stylesheets %}
    <link href="{% static "css/dietitian_clients.css" %}" rel="stylesheet">{% endblock %}
{% block additional_scripts %}
    <script src="{% static "js/client-search.js" %}" defer></script>
    <script src="{% static "js/clients.js" %}" defer type="module"></script>
{% endblock %}
{% block information %}
    <div class="clients-container">
        <table>
            <thead>
            <tr>
                <th>
                    <div class="search-wrapper">
                        <label for="search-name">Name</label>
                        <div class="input-wrapper">
                            <input id="search-client" type="text">
                            <i data-search-icon class="fa-solid fa-magnifying-glass fa-xs"></i>
                        </div>
                    </div>
                </th>
                <th>age</th>
                <th>active</th>
                <th>consistency</th>
                <th>expiration date</th>
            </tr>
            </thead>
            <tbody>
            {% for client in clients %}
                <tr data-client="{{ client }}">
                    <td>
                        {{ client }}
                        <div class="text-client-wrapper" data-text-client="{{ client.pk }}" data-name="{{ client }}">
                            Text
                            <i class="fa-solid fa-pen fa-xs"></i>
                        </div>
                    </td>
                    <td>agjadnkf</td>
                    <td>fsasf</td>
                    <td>fsaf</td>
                    <td>fasfa</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>


    </div>
{% endblock %}

dietplanr/panel/templates/panel/dietitian_clients.html
{% extends 'dietitian_panel_base.html' %}
{% load static %}
{% block title %}Clients{% endblock %}
{% block additional_stylesheets %}<link href="{% static "css/dietitian_clients.css" %}" rel="stylesheet">{% endblock %}
{% block information %}
    <div class="clients-container">
        <table>
            <thead>
                <tr>
                    <th>name</th>
                    <th>age</th>
                    <th>active</th>
                    <th>consistency</th>
                    <th>expiration date</th>
                </tr>
            </thead>
            <tbody>
                {% for client in clients %}
                    <tr>
                        <td>{{ client }}</td>
                        <td>agjadnkf</td>
                        <td>fsasf</td>
                        <td>fsaf</td>
                        <td>fasfa</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

dietplanr/panel/templates/panel/dietitian_profile_edit.html
{% extends 'dietitian_panel_base.html' %}
{% load static %}
{% block title %}Settings{% endblock %}
{% block additional_stylesheets %}
    <link href="{% static "css/settings.css" %}" rel="stylesheet">
{% endblock %}
{% block additional_scripts %}
    <script src="{% static "js/settings.js" %}" defer></script>
{% endblock %}
{% block information %}
    <div class="settings-container" data-container>
        {% if user.is_dietitian %}
            <form method="POST" class="profile-settings-wrapper">
                {% csrf_token %}
                <script>
                    const csrfToken = "{{ csrf_token }}";
                </script>

                <div class="input-group">
                    <textarea id="specialty" name="specialty" class="long-input" placeholder=" "></textarea>
                    <label for="specialty">Specialty</label>
                </div>
                <div class="input-group">
                    <textarea id="experience" name="experience" class="long-input" placeholder=" "></textarea>
                    <label for="experience">Experience</label>
                </div>
                <div class="input-group">
                    <textarea id="nutritional_philosophy" name="philosophy" class="long-input"
                              placeholder=" "></textarea>
                    <label for="nutritional_philosophy">Philosophy</label>
                </div>
                <div class="input-group">
                    <textarea id="some_more" name="somemore" class="long-input" placeholder=" "></textarea>
                    <label for="some_more">Some more</label>
                </div>
                <button type="submit" id="profile-settings-btn">SUBMIT</button>
            </form>
        {% endif %}

        <form class="user-settings">
            {% csrf_token %}
            <section class="user-settings-section">
                <div>
                    <label for="mail">Mail</label>
                    <input type="email" name="mail" id="mail" value="">
                </div>
                <div>
                    <label for="password">Password</label>
                    <input type="password" name="image" id="password" value="">
                </div>
                <div>
                    <label for="photo">Photo</label>
                    <input type="file" name="image" id="photo" value="">
                </div>
                <button type="submit">SUBMIT</button>
            </section>

        </form>
    </div>
{% endblock %}

dietplanr/panel/templates/panel/home.html
{% extends 'dietitian_panel_base.html' %}
{% load static %}
{% block additional_stylesheets %}
    <link href="{% static "css/home.css" %}" rel="stylesheet">
{% endblock %}
{% block additional_scripts %}
    <script src="{% static "js/home.js" %}" defer></script>
{% endblock %}
{% block information %}
    {#    <div class="container">#}
    {#        <div class="form">#}
    {#            <h3>Witaj, {{ user.first_name }}!</h3>#}
    {#            <a href="{% url 'panel:logout' %}">Wyloguj się</a>#}
    {#            <a href="{% url 'panel:user_edit_profile' %}">#}
    {#                Create a client profile#}
    {#            </a>#}
    {#            <a href="{% url 'panel:show_calendar' %}">#}
    {#                Calendar#}
    {#            </a>#}
    {#            <a href="{% url 'panel:login' %}">Login again</a>#}
    {#            {% if user.is_client %}#}
    {#                <a href="{% url 'tracker:register_activity' %}">#}
    {#                   Register activity#}
    {#                </a>#}
    {#            {% elif user.is_dietitian %}#}
    {#                <a href="{% url 'panel:show_clients' %}">#}
    {#                    Clients#}
    {#                </a>#}
    {#            {% endif %}#}
    {#        </div>#}
    {#    </div>#}
    <div class="home-container">
        <h1>Witaj {{ user.first_name }}!</h1>
        {% if user.is_dietitian %}
            <div class="overview-container">
                <div class="clients-activity-wrapper">
                    <p>Clients activity </p>
                    <div class="clients-span">

                    </div>

                </div>
                <div class="messages-wrapper">
                    <p> Messages </p>
                    <div class="messages-span">

                    </div>

                </div>
                <div class="appointments-activity-wrapper">
                    <p> Appointments </p>
                    <div class="appointments-span">

                    </div>
                </div>
            </div>
        {% endif %}
    </div>

{% endblock %}

dietplanr/panel/templates/panel/landing_page.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock %}
{% block stylesheets %}<link href="{% static "css/landing_page.css" %}" rel="stylesheet">{% endblock %}
{% block scripts %}<script src={% static "js/carousel.js" %} defer></script>{% endblock %}
{% block content %}
    <div class="container">
        <div class="img-wrapper">
            <img src="../../static/images/jason-briscoe-KTrov7eujms-unsplash.jpg">
            <div class="text">Ready to lead a healthier lifestyle with ease?</div>
            <img src="../../static/images/360_F_167925514_0KaT2pug6QURGwhl44Y0H77JhrJGhLVY.jpg">
        </div>
        <div class="carousel-container">
            <div class="carousel">
                <button class="prev" data-carousel-button="prev"><i class="fa-solid fa-angle-left"></i></button>
                <button class="next" data-carousel-button="next"><i class="fa-solid fa-angle-right"></i></button>
                <div class="slide" data-active>
                    <img src="../../static/images/christina-wocintechchat-com-eF7HN40WbAQ-unsplash.jpg">
                </div>
                <div class="slide">
                    <img src="../../static/images/linkedin-sales-solutions-VKJt1EZHlWs-unsplash.jpg">
                </div>
                <div class="slide">
                    <img src="../../static/images/360_F_167925514_0KaT2pug6QURGwhl44Y0H77JhrJGhLVY.jpg">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

dietplanr/panel/templates/panel/registration.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Register{% endblock %}
{% block stylesheets %}
    <link href="{% static "css/registration_and_loginout.css" %}" rel="stylesheet">{% endblock %}
{% block content %}
    <div class="container">
        <div class="form">
            <form method="post">
                {% csrf_token %}
                {{ form.as_div }}
                <button type="submit">Register</button>
            </form>
            {% if user.is_authenticated %}
                <a href="{% url 'panel:home' %}" class="button">Save changes</a>

            {% else %}
                <!-- Przycisk rejestracji jako klient -->
                <a href="{% url 'panel:registration' %}?is_client=True" class="button">Zarejestruj jako klient</a>

                <!-- Przycisk rejestracji jako dietetyk -->
                <a href="{% url 'panel:registration' %}?is_dietitian=True" class="button">Zarejestruj jako dietetyk</a>
            {% endif %}
        </div>
    </div>

{% endblock %}